# This rule is not used by the project chainplane itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the nodes.nodes.chainplane.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chainplane
    app.kubernetes.io/managed-by: kustomize
  name: blockchainnode-editor-role
rules:
- apiGroups:
  - nodes.nodes.chainplane.io
  resources:
  - blockchainnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodes.nodes.chainplane.io
  resources:
  - blockchainnodes/status
  verbs:
  - get
