/*
Copyright (c) 2026 tazhate <hate@tazhate.ru>
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package adapters

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"

	chainsv1alpha2 "github.com/tazhate/chainplane/api/v1alpha2"
)

// --------------------------------------------------------------------------
// Constants
// --------------------------------------------------------------------------

const (

	// cosmosBlockTime is the average Cosmos Hub block interval used to estimate network tip.
	cosmosBlockTime = 6.5 // seconds
)

// --------------------------------------------------------------------------
// Type
// --------------------------------------------------------------------------

type cosmosAdapter struct {
	protocolAdapter
}

// --------------------------------------------------------------------------
// Registration
// --------------------------------------------------------------------------

func init() {
	Register(chainsv1alpha2.ChainCosmos, &cosmosAdapter{
		protocolAdapter: protocolAdapter{livenessPort: 26657},
	})
}

// --------------------------------------------------------------------------
// Config (static raw string)
// --------------------------------------------------------------------------

const cosmosConfig = `# Cosmos Hub (cosmoshub-4) app.toml overrides
# Full config is generated by gaiad init -- this is the override toml merged at startup.
[api]
enable = true
address = "tcp://0.0.0.0:1317"
enabled-unsafe-cors = true

[grpc]
enable = false

[telemetry]
enabled = true
prometheus-retention-time = 60
`

// --------------------------------------------------------------------------
// Response types
// --------------------------------------------------------------------------

type cosmosStatusResponse struct {
	Result struct {
		SyncInfo struct {
			LatestBlockHeight string `json:"latest_block_height"`
			LatestBlockTime   string `json:"latest_block_time"`
			CatchingUp        bool   `json:"catching_up"`
		} `json:"sync_info"`
	} `json:"result"`
}

type cosmosConsensusStateResponse struct {
	Result struct {
		RoundState struct {
			HeightRoundStep string `json:"height/round/step"`
		} `json:"round_state"`
	} `json:"result"`
}

// --------------------------------------------------------------------------
// Interface methods
// --------------------------------------------------------------------------

func (a *cosmosAdapter) DefaultImage(client string) string {
	return DefaultImageFor(chainsv1alpha2.ChainCosmos, client)
}

func (a *cosmosAdapter) ConfigTemplate(_ chainsv1alpha2.ChainInstanceSpec) (string, string, error) {
	return "app.toml", cosmosConfig, nil
}

// cosmosHubNode bootstraps cosmoshub-4 through CometBFT state sync: a
// replay from genesis needs every historical gaiad, so the node restores a
// recent snapshot instead (or resumes a MinIO snapshot restore). Genesis
// is the gzipped file of cosmos/mainnet, pinned to a commit.
var cosmosHubNode = cosmosNode{
	Binary:          "gaiad",
	ChainID:         "cosmoshub-4",
	GenesisURL:      "https://raw.githubusercontent.com/cosmos/mainnet/70d6682e987b81ec6cd73405e40aaecbf9f51912/genesis/genesis.cosmoshub-4.json.gz",
	GenesisSHA256:   "7fe946e6bb3c378da546767f4d078585c38f256c8ec17888d71aeee3b7edd5c7",
	GenesisFormat:   genesisGzip,
	Seeds:           "ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:14956,8542cd7e6bf9d260fef543bc49e59be5a3fa9074@seed.publicnode.com:26656,b85358e035343a3b15e77e1102857dcdaf70053b@seeds.bluestake.net:28156,00bf1f9d3c65137dc99c40cd03864384ce0ef7c3@cosmoshub-mainnet-seed.itrocket.net:34656",
	PersistentPeers: "1da54d20c7339713f1d6d28dd2117087dd33d0ca@cosmos-seed.icycro.org:26656,2441723e318545be469d43611d331e3271477ede@cosmoshub-mainnet-peer.itrocket.net:34656",
	StateSyncRPC:    []string{"https://cosmos-rpc.polkachu.com:443", "https://cosmoshub.rpc.kjnodes.com:443"},
}

// ContainerCommand initializes /data on first start; see cosmosNode.Command.
// The image ENTRYPOINT is `gaiad start` without --home, so it is replaced.
func (a *cosmosAdapter) ContainerCommand(_ chainsv1alpha2.ChainInstanceSpec) []string {
	return cosmosHubNode.Command()
}

// ContainerArgs are `gaiad start` flags.
func (a *cosmosAdapter) ContainerArgs(_ chainsv1alpha2.ChainInstanceSpec) []string {
	return []string{
		"--minimum-gas-prices", "0.0025uatom",
		"--rpc.laddr", "tcp://0.0.0.0:26657",
		"--p2p.laddr", "tcp://0.0.0.0:26656",
		"--api.enable",
		"--api.address", "tcp://0.0.0.0:1317",
		"--grpc.enable=false",
	}
}

// HealthCheck queries Tendermint RPC /status on port 26657.
func (a *cosmosAdapter) HealthCheck(ctx context.Context, rpcURL string) (SyncStatus, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rpcURL+"/status", nil)
	if err != nil {
		return SyncStatus{}, fmt.Errorf("call Cosmos status endpoint: %w", err)
	}
	resp, err := rpcClient.Do(req)
	if err != nil {
		return SyncStatus{}, fmt.Errorf("cosmos health probe: %w", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(io.LimitReader(resp.Body, maxResponseBytes))

	var status cosmosStatusResponse
	if err := json.Unmarshal(body, &status); err != nil {
		return SyncStatus{}, fmt.Errorf("decode Cosmos status payload: %w", err)
	}

	height := parseDecimalInt64(status.Result.SyncInfo.LatestBlockHeight)
	syncing := status.Result.SyncInfo.CatchingUp

	// During CometBFT state sync the node reports height=0 for 30-60 minutes.
	if height == 0 && syncing {
		p := pseudoBlock()
		return SyncStatus{IsSyncing: true, CurrentBlock: p, HighestBlock: p + 1, Progress: 0}, nil
	}

	highestBlock := height
	if syncing {
		if blockTime, err := time.Parse(time.RFC3339Nano, status.Result.SyncInfo.LatestBlockTime); err == nil {
			lag := time.Since(blockTime).Seconds()
			if lag > cosmosBlockTime {
				highestBlock = height + int64(lag/cosmosBlockTime)
			}
		}
		if tip := cosmosNetworkTip(ctx, rpcURL); tip > highestBlock {
			highestBlock = tip
		}
	}

	var progress float64
	if !syncing {
		progress = 100.0
	} else {
		progress = progressFromBlocks(height, highestBlock)
	}

	// best-effort peer count from /net_info
	var peers int32
	if req2, err2 := http.NewRequestWithContext(ctx, http.MethodGet, rpcURL+"/net_info", nil); err2 == nil {
		if resp2, err2 := (&http.Client{Timeout: 5 * time.Second}).Do(req2); err2 == nil {
			defer resp2.Body.Close()
			body2, _ := io.ReadAll(io.LimitReader(resp2.Body, maxResponseBytes))
			var netInfo struct {
				Result struct {
					NPeers string `json:"n_peers"`
				} `json:"result"`
			}
			if json.Unmarshal(body2, &netInfo) == nil {
				peers = int32(parseDecimalInt64(netInfo.Result.NPeers))
			}
		}
	}

	return SyncStatus{
		IsSyncing:    syncing,
		CurrentBlock: height,
		HighestBlock: highestBlock,
		Progress:     progress,
		Peers:        peers,
	}, nil
}

// StartupProbe gives Cosmos up to 1h (120x30s) to complete state sync.
func (a *cosmosAdapter) StartupProbe(_ chainsv1alpha2.ChainInstanceSpec) *corev1.Probe {
	return tcpProbe(26657, 30, 30, 10, 120)
}

func (a *cosmosAdapter) ContainerPorts(_ chainsv1alpha2.ChainInstanceSpec) []corev1.ContainerPort {
	return []corev1.ContainerPort{
		{Name: "rpc", ContainerPort: 26657, Protocol: corev1.ProtocolTCP},
		{Name: "api", ContainerPort: 1317, Protocol: corev1.ProtocolTCP},
		{Name: "p2p", ContainerPort: 26656, Protocol: corev1.ProtocolTCP},
		{Name: "metrics", ContainerPort: 26660, Protocol: corev1.ProtocolTCP},
	}
}

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

// cosmosNetworkTip queries the local node's /consensus_state to read the network tip.
func cosmosNetworkTip(ctx context.Context, rpcURL string) int64 {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rpcURL+"/consensus_state", nil)
	if err != nil {
		return 0
	}
	resp, err := rpcClient.Do(req)
	if err != nil {
		return 0
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(io.LimitReader(resp.Body, maxResponseBytes))

	var cs cosmosConsensusStateResponse
	if err := json.Unmarshal(body, &cs); err != nil {
		return 0
	}
	// HeightRoundStep is formatted as "30178804/0/1"
	var h, r, s int64
	_, _ = fmt.Sscanf(cs.Result.RoundState.HeightRoundStep, "%d/%d/%d", &h, &r, &s)
	return h
}

func (a *cosmosAdapter) DefaultResources() ResourceDefaults {
	return ResourceDefaults{
		CPURequest:    resource.MustParse("4"),
		MemoryRequest: resource.MustParse("8Gi"),
		Storage:       resource.MustParse("500Gi"),
	}
}

func (a *cosmosAdapter) VersionPolicy() ChainVersionPolicy {
	return ChainVersionPolicy{
		Registry:   "ghcr.io",
		Repository: "cosmos/gaia",
		TagPattern: `^v\d+\.\d+\.\d+$`,
	}
}
