package adapters

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"

	nodesv1alpha1 "github.com/tazhate/chainplane/api/v1alpha1"
)

// --------------------------------------------------------------------------
// Constants
// --------------------------------------------------------------------------

const (

	// cosmosBlockTime is the average Cosmos Hub block interval used to estimate network tip.
	cosmosBlockTime = 6.5 // seconds
)

// --------------------------------------------------------------------------
// Type
// --------------------------------------------------------------------------

type cosmosAdapter struct {
	baseAdapter
}

// --------------------------------------------------------------------------
// Registration
// --------------------------------------------------------------------------

func init() {
	Register(nodesv1alpha1.ChainCosmos, &cosmosAdapter{
		baseAdapter: baseAdapter{livenessPort: 26657},
	})
}

// --------------------------------------------------------------------------
// Config (static raw string)
// --------------------------------------------------------------------------

const cosmosConfig = `# Cosmos Hub (cosmoshub-4) node config
# Full config is generated by gaiad init -- this is the override toml merged at startup.
[api]
enable = true
address = "tcp://0.0.0.0:1317"
enabled-unsafe-cors = true

[grpc]
enable = false

[telemetry]
enabled = true
prometheus-retention-time = 60
`

// --------------------------------------------------------------------------
// Response types
// --------------------------------------------------------------------------

type cosmosStatusResponse struct {
	Result struct {
		SyncInfo struct {
			LatestBlockHeight string `json:"latest_block_height"`
			LatestBlockTime   string `json:"latest_block_time"`
			CatchingUp        bool   `json:"catching_up"`
		} `json:"sync_info"`
	} `json:"result"`
}

type cosmosConsensusStateResponse struct {
	Result struct {
		RoundState struct {
			HeightRoundStep string `json:"height/round/step"`
		} `json:"round_state"`
	} `json:"result"`
}

// --------------------------------------------------------------------------
// Interface methods
// --------------------------------------------------------------------------

func (a *cosmosAdapter) DefaultImage(client string) string {
	return DefaultImageFor(nodesv1alpha1.ChainCosmos, client)
}

func (a *cosmosAdapter) ConfigTemplate(_ nodesv1alpha1.BlockchainNodeSpec) (string, string, error) {
	return "app.toml", cosmosConfig, nil
}

// ContainerCommand initializes Cosmos Hub node with CometBFT state sync.
// cosmoshub-4 genesis.json uses old Cosmos SDK field names incompatible with gaiad v27.
// CometBFT state sync bypasses genesis replay entirely.
func (a *cosmosAdapter) ContainerCommand(_ nodesv1alpha1.BlockchainNodeSpec) []string {
	return []string{
		"sh", "-c",
		`set -e
GAIAD=/usr/local/bin/gaiad
HOME=/data

INITIALIZED="$HOME/.initialized"

# Detect MinIO snapshot restore
SNAPSHOT_BOOT=0
if [ -d "$HOME/data/application.db" ]; then
  SNAPSHOT_BOOT=1
fi

# Detect stale/partial state sync data
NEED_REINIT=0
if [ -f "$INITIALIZED" ] && [ -f "$HOME/config/config.toml" ]; then
  if ! grep -q "^enable = true" "$HOME/config/config.toml" 2>/dev/null; then
    if [ "$SNAPSHOT_BOOT" = "0" ]; then
      echo "Detected missing state sync config; forcing reinit"
      NEED_REINIT=1
    fi
  else
    PV_HEIGHT=$(grep -oE '"height":"[0-9]+"' "$HOME/data/priv_validator_state.json" 2>/dev/null | grep -oE '[0-9]+' || echo "0")
    if [ "$PV_HEIGHT" = "0" ]; then
      APP_DB_SIZE=$(stat -c%s "$HOME/data/application.db" 2>/dev/null || echo "0")
      if [ "$APP_DB_SIZE" -gt 104857600 ]; then
        echo "State sync in progress (application.db=${APP_DB_SIZE} bytes, PV height=0); NOT wiping — letting sync continue"
      else
        echo "Detected incomplete state sync (priv_validator_state height=0, application.db=${APP_DB_SIZE}); wiping and resyncing"
        NEED_REINIT=1
      fi
    fi
  fi
fi
if [ ! -f "$INITIALIZED" ]; then
  NEED_REINIT=1
fi

if [ "$NEED_REINIT" = "1" ]; then
  if [ "$SNAPSHOT_BOOT" = "1" ]; then
    echo "Snapshot data detected (application.db present) — booting from snapshot..."
    TMPINIT=$(mktemp -d)
    $GAIAD init "rpc-node" --chain-id cosmoshub-4 --home "$TMPINIT" --overwrite 2>/dev/null || \
      $GAIAD init "rpc-node" --chain-id cosmoshub-4 --home "$TMPINIT"
    mkdir -p "$HOME/config"
    cp "$TMPINIT/config/config.toml" "$HOME/config/config.toml"
    rm -rf "$TMPINIT"
    rm -f "$HOME/config/priv_validator_key.json" "$HOME/config/node_key.json" 2>/dev/null || true
    echo "Config generated for snapshot boot"
  else
    echo "Running init (clean slate)..."
    rm -rf "$HOME/data/" "$HOME/wasm/" 2>/dev/null || true
    rm -f "$HOME/config/priv_validator_key.json" "$HOME/config/node_key.json" 2>/dev/null || true
    mkdir -p "$HOME/data"
    rm -f "$HOME/config/config.toml"
    $GAIAD init "rpc-node" --chain-id cosmoshub-4 --home "$HOME" --overwrite
    echo "gaiad init complete"
  fi

  wget -qO "$HOME/config/genesis.json" https://snapshots.polkachu.com/genesis/cosmos/genesis.json
  echo "genesis downloaded"

  sed -i 's/^seeds = ""/seeds = "ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:14956,20e1000e88125698264454a884812746c2eb4807@seeds.lavenderfive.com:14956"/' "$HOME/config/config.toml"
  sed -i 's/^persistent_peers = ""/persistent_peers = "d9bfa29e0cf9c4ce0cc9c26d98e5d97228f93b0b@65.109.88.38:13456"/' "$HOME/config/config.toml"

  if [ "$SNAPSHOT_BOOT" = "0" ]; then
    SNAP_RPC="https://cosmos-rpc.polkachu.com"
    LATEST_HEIGHT=$(wget -qO- "$SNAP_RPC/block" 2>/dev/null | grep -oE '"height":"[0-9]+"' | head -1 | grep -oE '[0-9]+' || true)
    if [ -n "$LATEST_HEIGHT" ]; then
      TRUST_HEIGHT=$((LATEST_HEIGHT - 2000))
      TRUST_HASH=$(wget -qO- "$SNAP_RPC/block?height=$TRUST_HEIGHT" 2>/dev/null | grep -oE '"hash":"[0-9A-F]{64}"' | head -1 | grep -oE '[0-9A-F]{64}' || true)
      if [ -n "$TRUST_HASH" ]; then
        awk -v h="$TRUST_HEIGHT" -v hash="$TRUST_HASH" '
          /^\[statesync\]/{in_ss=1}
          /^\[/ && !/^\[statesync\]/{in_ss=0}
          in_ss && /^enable = false/{print "enable = true"; next}
          in_ss && /^rpc_servers = ""/{print "rpc_servers = \"https://cosmos-rpc.polkachu.com:443,https://cosmoshub.rpc.kjnodes.com:443\""; next}
          in_ss && /^trust_height = 0/{print "trust_height = " h; next}
          in_ss && /^trust_hash = ""/{print "trust_hash = \"" hash "\""; next}
          {print}
        ' "$HOME/config/config.toml" > /tmp/cfg.toml && mv /tmp/cfg.toml "$HOME/config/config.toml"
        echo "State sync configured: trust_height=$TRUST_HEIGHT trust_hash=$TRUST_HASH"
      else
        echo "WARNING: could not fetch trust_hash; falling back to full sync"
      fi
    else
      echo "WARNING: could not fetch latest height; falling back to full sync"
    fi
  else
    echo "Snapshot boot: state sync disabled (node will resume from snapshot height)"
  fi

  touch "$INITIALIZED"
  echo "Init complete"
fi

exec $GAIAD start --home "$HOME" \
  --minimum-gas-prices 0.0025uatom \
  --rpc.laddr tcp://0.0.0.0:26657 \
  --p2p.laddr tcp://0.0.0.0:26656 \
  --api.enable \
  --api.address tcp://0.0.0.0:1317 \
  --grpc.enable=false`,
	}
}

// HealthCheck queries Tendermint RPC /status on port 26657.
func (a *cosmosAdapter) HealthCheck(ctx context.Context, rpcURL string) (SyncStatus, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rpcURL+"/status", nil)
	if err != nil {
		return SyncStatus{}, fmt.Errorf("cosmos health request: %w", err)
	}
	resp, err := rpcClient.Do(req)
	if err != nil {
		return SyncStatus{}, fmt.Errorf("cosmos health: %w", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(io.LimitReader(resp.Body, maxResponseBytes))

	var status cosmosStatusResponse
	if err := json.Unmarshal(body, &status); err != nil {
		return SyncStatus{}, fmt.Errorf("cosmos status parse: %w", err)
	}

	height := parseDecimalInt64(status.Result.SyncInfo.LatestBlockHeight)
	syncing := status.Result.SyncInfo.CatchingUp

	// During CometBFT state sync the node reports height=0 for 30-60 minutes.
	if height == 0 && syncing {
		p := pseudoBlock()
		return SyncStatus{IsSyncing: true, CurrentBlock: p, HighestBlock: p + 1, Progress: 0}, nil
	}

	highestBlock := height
	if syncing {
		if blockTime, err := time.Parse(time.RFC3339Nano, status.Result.SyncInfo.LatestBlockTime); err == nil {
			lag := time.Since(blockTime).Seconds()
			if lag > cosmosBlockTime {
				highestBlock = height + int64(lag/cosmosBlockTime)
			}
		}
		if tip := cosmosNetworkTip(ctx, rpcURL); tip > highestBlock {
			highestBlock = tip
		}
	}

	var progress float64
	if !syncing {
		progress = 100.0
	} else {
		progress = progressFromBlocks(height, highestBlock)
	}

	// best-effort peer count from /net_info
	var peers int32
	if req2, err2 := http.NewRequestWithContext(ctx, http.MethodGet, rpcURL+"/net_info", nil); err2 == nil {
		if resp2, err2 := (&http.Client{Timeout: 5 * time.Second}).Do(req2); err2 == nil {
			defer resp2.Body.Close()
			body2, _ := io.ReadAll(io.LimitReader(resp2.Body, maxResponseBytes))
			var netInfo struct {
				Result struct {
					NPeers string `json:"n_peers"`
				} `json:"result"`
			}
			if json.Unmarshal(body2, &netInfo) == nil {
				peers = int32(parseDecimalInt64(netInfo.Result.NPeers))
			}
		}
	}

	return SyncStatus{
		IsSyncing:    syncing,
		CurrentBlock: height,
		HighestBlock: highestBlock,
		Progress:     progress,
		Peers:        peers,
	}, nil
}

// StartupProbe gives Cosmos up to 1h (120x30s) to complete state sync.
func (a *cosmosAdapter) StartupProbe(_ nodesv1alpha1.BlockchainNodeSpec) *corev1.Probe {
	return tcpProbe(26657, 30, 30, 10, 120)
}

func (a *cosmosAdapter) ContainerPorts(_ nodesv1alpha1.BlockchainNodeSpec) []corev1.ContainerPort {
	return []corev1.ContainerPort{
		{Name: "rpc", ContainerPort: 26657, Protocol: corev1.ProtocolTCP},
		{Name: "api", ContainerPort: 1317, Protocol: corev1.ProtocolTCP},
		{Name: "p2p", ContainerPort: 26656, Protocol: corev1.ProtocolTCP},
		{Name: "metrics", ContainerPort: 26660, Protocol: corev1.ProtocolTCP},
	}
}

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

// cosmosNetworkTip queries the local node's /consensus_state to read the network tip.
func cosmosNetworkTip(ctx context.Context, rpcURL string) int64 {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rpcURL+"/consensus_state", nil)
	if err != nil {
		return 0
	}
	resp, err := rpcClient.Do(req)
	if err != nil {
		return 0
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(io.LimitReader(resp.Body, maxResponseBytes))

	var cs cosmosConsensusStateResponse
	if err := json.Unmarshal(body, &cs); err != nil {
		return 0
	}
	// HeightRoundStep is formatted as "30178804/0/1"
	var h, r, s int64
	_, _ = fmt.Sscanf(cs.Result.RoundState.HeightRoundStep, "%d/%d/%d", &h, &r, &s)
	return h
}

func (a *cosmosAdapter) DefaultResources() ResourceDefaults {
	return ResourceDefaults{
		CPURequest:    resource.MustParse("4"),
		MemoryRequest: resource.MustParse("8Gi"),
		Storage:       resource.MustParse("500Gi"),
	}
}

func (a *cosmosAdapter) VersionPolicy() ChainVersionPolicy {
	return ChainVersionPolicy{
		Registry:   "ghcr.io",
		Repository: "cosmos/gaia",
		TagPattern: `^v\d+\.\d+\.\d+$`,
	}
}
