/*
Copyright (c) 2026 tazhate <hate@tazhate.ru>
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package adapters

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"text/template"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"

	chainsv1alpha2 "github.com/tazhate/chainplane/api/v1alpha2"
)

// --------------------------------------------------------------------------
// Constants
// --------------------------------------------------------------------------

const (
	rethMetricsPort       = int32(9001)
	gethMetricsPort       = int32(6060)
	erigonMetricsPort     = int32(6060)
	nethermindMetricsPort = int32(9091)
)

// --------------------------------------------------------------------------
// Type
// --------------------------------------------------------------------------

type ethereumAdapter struct {
	protocolAdapter
}

// --------------------------------------------------------------------------
// Registration
// --------------------------------------------------------------------------

func init() {
	eth := &ethereumAdapter{protocolAdapter: protocolAdapter{livenessPort: 8545}}
	Register(chainsv1alpha2.ChainEthereum, eth)
	Register(chainsv1alpha2.ChainEthereumArchive, eth)
}

// --------------------------------------------------------------------------
// Clients
// --------------------------------------------------------------------------

// Every client keeps its chain in /data, serves JSON-RPC on 8545 and
// WebSocket on 8546, and opens the Engine API on 8551 for the beacon node
// (ethereum-beacon dials http://ethereum:8551). The Engine API secret is
// /data/jwt.hex, generated by the client on first start; the beacon node
// needs the same file. Reth keeps it at the same path by default.
const (
	ethDataDir    = "/data"
	ethJWTPath    = "/data/jwt.hex"
	ethEnginePort = int32(8551)
	ethP2PPort    = int32(30303)

	// gethConfigPath is where the rendered geth TOML is mounted.
	gethConfigPath = "/config/config.toml"
)

// ethClient returns the execution client of spec: geth, reth, erigon or
// nethermind. Anything else runs the default image, which is Nethermind.
func ethClient(spec chainsv1alpha2.ChainInstanceSpec) string {
	switch c := strings.ToLower(spec.Client); c {
	case "geth", "reth", "erigon":
		return c
	default:
		return "nethermind"
	}
}

// ethNetwork returns the network name the clients use: mainnet, or sepolia
// for testnet.
func ethNetwork(spec chainsv1alpha2.ChainInstanceSpec) string {
	if spec.Network == chainsv1alpha2.NetworkTestnet {
		return "sepolia"
	}
	return "mainnet"
}

// ethArchive reports whether the node keeps all historical state:
// ethereum-archive, or nodeType archive on ethereum.
func ethArchive(spec chainsv1alpha2.ChainInstanceSpec) bool {
	return spec.Chain == chainsv1alpha2.ChainEthereumArchive || spec.NodeType == chainsv1alpha2.NodeTypeArchive
}

// gethConfigTpl is the geth TOML, read with --config. Field names follow the
// geth config structs (geth dumpconfig prints them); durations are
// nanoseconds, since geth decodes time.Duration from TOML integers only.
// The network comes from the --sepolia flag, not from the file: a TOML
// NetworkId does not change the genesis.
var gethConfigTpl = template.Must(template.New("geth").Parse(`# geth config for {{ .Chain }} {{ .Network }}
[Eth]
{{- if .Archive }}
SyncMode = "full"
NoPruning = true
Preimages = true
TransactionHistory = 0
{{- else }}
SyncMode = "snap"
{{- end }}

[Node]
DataDir = "/data"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool"]
WSHost = "0.0.0.0"
WSPort = 8546
WSModules = ["eth", "net", "web3"]
WSOrigins = ["*"]
AuthAddr = "0.0.0.0"
AuthPort = 8551
AuthVirtualHosts = ["*"]
JWTSecret = "/data/jwt.hex"

[Node.P2P]
MaxPeers = 50
ListenAddr = ":30303"

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
`))

// ethNethermind runs Nethermind on its built-in mainnet or sepolia config
// (the _archive variant for archive nodes) with the data directory on the
// data volume. The Engine API moves from the built-in localhost:8551 to
// 0.0.0.0:8551 so the beacon node in another pod can reach it.
func ethNethermind(spec chainsv1alpha2.ChainInstanceSpec) nethermindNode {
	config := ethNetwork(spec)
	if ethArchive(spec) {
		config += "_archive"
	}
	return nethermindNode{
		Config:      config,
		P2PPort:     ethP2PPort,
		MetricsPort: nethermindMetricsPort,
		Extra: []nethermindSetting{
			{"JsonRpc", "EngineHost", "0.0.0.0"},
			{"JsonRpc", "EnginePort", ethEnginePort},
			{"JsonRpc", "JwtSecretFile", ethJWTPath},
		},
	}
}

// gethArgs reads the rendered TOML; metrics are flags because geth's TOML
// has no switch for them.
func gethArgs(spec chainsv1alpha2.ChainInstanceSpec) []string {
	args := []string{"--config", gethConfigPath}
	if ethNetwork(spec) == "sepolia" {
		args = append(args, "--sepolia")
	}
	return append(args, "--metrics", "--metrics.addr", "0.0.0.0", "--metrics.port", "6060")
}

// erigonArgs configures Erigon 2 by flags. Erigon 2 keeps everything unless
// told to prune, so a full node prunes history, receipts, tx lookup and call
// traces older than 90k blocks and an archive node passes no --prune.
func erigonArgs(spec chainsv1alpha2.ChainInstanceSpec) []string {
	args := []string{
		"--chain", ethNetwork(spec),
		"--datadir", ethDataDir,
		"--port", "30303",
		"--http", "--http.addr", "0.0.0.0", "--http.port", "8545", "--http.vhosts", "*",
		"--http.api", "eth,erigon,net,web3,txpool",
		"--ws", "--ws.port", "8546",
		"--authrpc.addr", "0.0.0.0", "--authrpc.port", "8551", "--authrpc.vhosts", "*",
		"--authrpc.jwtsecret", ethJWTPath,
		"--metrics", "--metrics.addr", "0.0.0.0", "--metrics.port", "6060",
	}
	if !ethArchive(spec) {
		args = append(args, "--prune", "hrtc")
	}
	return args
}

// rethArgs configures reth by flags. reth keeps all history by default;
// --full prunes it. reth refuses an --authrpc.jwtsecret file that does not
// exist yet, so the secret stays at its default, <datadir>/jwt.hex.
func rethArgs(spec chainsv1alpha2.ChainInstanceSpec) []string {
	args := []string{
		"node",
		"--chain", ethNetwork(spec),
		"--datadir", ethDataDir,
		"--port", "30303",
		"--http", "--http.addr", "0.0.0.0", "--http.port", "8545", "--http.api", "eth,net,web3,txpool",
		"--ws", "--ws.addr", "0.0.0.0", "--ws.port", "8546",
		"--authrpc.addr", "0.0.0.0", "--authrpc.port", "8551",
		"--metrics", "0.0.0.0:9001",
	}
	if !ethArchive(spec) {
		args = append(args, "--full")
	}
	return args
}

// --------------------------------------------------------------------------
// Interface methods
// --------------------------------------------------------------------------

func (a *ethereumAdapter) DefaultImage(client string) string {
	// v1.15+ changed DB format (PBSS). Existing geth nodes must resync when upgrading from v1.14.x.
	return DefaultImageFor(chainsv1alpha2.ChainEthereum, client)
}

// ConfigTemplate renders the geth TOML for geth and the reference
// nethermind.json for Nethermind (the settings themselves go in as flags).
// reth and Erigon are configured by flags only and get no file.
func (a *ethereumAdapter) ConfigTemplate(spec chainsv1alpha2.ChainInstanceSpec) (string, string, error) {
	switch ethClient(spec) {
	case "geth":
		var buf bytes.Buffer
		err := gethConfigTpl.Execute(&buf, struct {
			Chain   chainsv1alpha2.Chain
			Network string
			Archive bool
		}{spec.Chain, ethNetwork(spec), ethArchive(spec)})
		if err != nil {
			return "", "", fmt.Errorf("ethereum geth config: %w", err)
		}
		return "config.toml", buf.String(), nil
	case "nethermind":
		cfg, err := ethNethermind(spec).configFile()
		return nethermindConfigFile, cfg, err
	default:
		return "", "", nil
	}
}

func (a *ethereumAdapter) HealthCheck(ctx context.Context, rpcURL string) (SyncStatus, error) {
	// Call eth_syncing — may timeout during heavy stage work (IndexStorageHistory, etc.)
	syncResult, syncErr := callRPC(ctx, rpcURL, "eth_syncing", nil)

	// Always try eth_blockNumber even if eth_syncing timed out — it's a lighter call.
	var currentBlock int64
	if blockResult, blockErr := callRPC(ctx, rpcURL, "eth_blockNumber", nil); blockErr == nil {
		var blockHex string
		if json.Unmarshal(blockResult, &blockHex) == nil {
			currentBlock = hexToInt64(blockHex)
		}
	}

	if syncErr != nil {
		if isContextTimeout(syncErr) {
			// RPC timeout during heavy stage work (SenderRecovery, Execution, IndexStorageHistory, etc.)
			// is normal for Reth/Erigon and must not trigger a Degraded restart.
			return SyncStatus{
				IsSyncing:    true,
				CurrentBlock: currentBlock,
				HighestBlock: currentBlock,
				Progress:     100.0,
				StallExempt:  true,
			}, nil
		}
		return SyncStatus{}, fmt.Errorf("eth_syncing: %w", syncErr)
	}

	peers := evmPeerCount(ctx, rpcURL)

	var syncingFalse bool
	if err := json.Unmarshal(syncResult, &syncingFalse); err == nil && !syncingFalse {
		return SyncStatus{
			IsSyncing:    false,
			CurrentBlock: currentBlock,
			HighestBlock: currentBlock,
			Progress:     100.0,
			Peers:        peers,
		}, nil
	}

	var syncObj struct {
		CurrentBlock string `json:"currentBlock"`
		HighestBlock string `json:"highestBlock"`
		Stages       []struct {
			StageName   string `json:"name"`
			BlockNumber string `json:"block"`
		} `json:"stages"`
	}
	if err := json.Unmarshal(syncResult, &syncObj); err != nil {
		return SyncStatus{}, fmt.Errorf("parse eth_syncing: %w", err)
	}

	// Polygon-specific stages that are always 0 and must be excluded.
	polygonStages := map[string]bool{"BorHeimdall": true, "Translation": true}

	// Erigon post-sync indexing stages: blocks are fully downloaded but indexing lags.
	// Treat as synced (current = highest) to avoid false stall detection.
	postSyncStages := map[string]bool{
		"IndexStorageHistory":   true,
		"IndexAccountHistory":   true,
		"IndexLogAddressTopics": true,
		"LogIndex":              true,
		"TxLookup":              true,
		"CallTraces":            true,
		"Finish":                true,
	}

	var current, highest int64
	if len(syncObj.Stages) > 0 {
		current = -1 // sentinel
		var bottleneckStage string
		var bottleneckBlock int64
		for _, s := range syncObj.Stages {
			if polygonStages[s.StageName] {
				continue
			}
			n := hexToInt64(s.BlockNumber)
			if n > highest {
				highest = n
			}
			if current < 0 || n < current {
				current = n
				bottleneckStage = s.StageName
				bottleneckBlock = n
			}
		}
		if current < 0 {
			current = 0
		}
		_ = bottleneckBlock

		if highest > 0 && postSyncStages[bottleneckStage] {
			// Blocks are all synced; only post-sync indexing remains.
			current = highest
		}
	} else {
		current = currentBlock
		highest = hexToInt64(syncObj.HighestBlock)
	}

	progress := progressFromBlocks(current, highest)

	return SyncStatus{
		IsSyncing:    true,
		CurrentBlock: current,
		HighestBlock: highest,
		Progress:     progress,
		Peers:        peers,
		StallExempt:  true,
	}, nil
}

func (a *ethereumAdapter) LivenessProbe(spec chainsv1alpha2.ChainInstanceSpec) *corev1.Probe {
	port := int32(8545)
	if spec.RPC.Port > 0 {
		port = spec.RPC.Port
	}
	return tcpProbe(port, 300, 30, 10, 3) // Reth/Erigon startup time before RPC ready
}

func (a *ethereumAdapter) ContainerPorts(spec chainsv1alpha2.ChainInstanceSpec) []corev1.ContainerPort {
	return append(evmPorts(ethP2PPort),
		corev1.ContainerPort{Name: "engine", ContainerPort: ethEnginePort, Protocol: corev1.ProtocolTCP},
		corev1.ContainerPort{Name: "metrics", ContainerPort: ethMetricsPort(spec), Protocol: corev1.ProtocolTCP},
	)
}

// ContainerArgs points the client at the data volume, the network and the
// RPC, Engine API and metrics endpoints.
func (a *ethereumAdapter) ContainerArgs(spec chainsv1alpha2.ChainInstanceSpec) []string {
	switch ethClient(spec) {
	case "geth":
		return gethArgs(spec)
	case "reth":
		return rethArgs(spec)
	case "erigon":
		return erigonArgs(spec)
	default:
		return ethNethermind(spec).args()
	}
}

// ethMetricsPort returns the Prometheus metrics port of the client.
func ethMetricsPort(spec chainsv1alpha2.ChainInstanceSpec) int32 {
	switch ethClient(spec) {
	case "reth":
		return rethMetricsPort
	case "erigon":
		return erigonMetricsPort
	case "geth":
		return gethMetricsPort
	default:
		return nethermindMetricsPort
	}
}

func (a *ethereumAdapter) VersionPolicy() ChainVersionPolicy {
	return ChainVersionPolicy{
		Registry:   "docker.io",
		Repository: "nethermind/nethermind",
		TagPattern: `^\d+\.\d+\.\d+$`,
	}
}

func (a *ethereumAdapter) ClientVersionPolicies() map[string]ChainVersionPolicy {
	semverTag := `^v\d+\.\d+\.\d+$`
	return map[string]ChainVersionPolicy{
		"erigon":     {Registry: "docker.io", Repository: "erigontech/erigon", TagPattern: semverTag},
		"geth":       {Registry: "docker.io", Repository: "ethereum/client-go", TagPattern: semverTag},
		"nethermind": a.VersionPolicy(),
		"reth":       {Registry: "ghcr.io", Repository: "paradigmxyz/reth", TagPattern: semverTag},
	}
}

func (a *ethereumAdapter) DefaultResources() ResourceDefaults {
	return ResourceDefaults{
		CPURequest:    resource.MustParse("8"),
		MemoryRequest: resource.MustParse("8Gi"),
		Storage:       resource.MustParse("2Ti"),
	}
}
