// Code generated by cmd/versioncheck on 2026-10-01. DO NOT EDIT.

package adapters

import (
	"strings"

	chainsv1alpha2 "github.com/tazhate/chainplane/api/v1alpha2"
)

//go:generate go run ../../cmd/versioncheck --update

// chainDefaultImages maps each chain and optional client to its default container image.
// Inner key: lowercase client name, or "" for the chain default.
var chainDefaultImages = map[chainsv1alpha2.Chain]map[string]string{
	chainsv1alpha2.ChainAbstract: {
		"": "matterlabs/external-node:v29.17.0",
	},
	chainsv1alpha2.ChainAptos: {
		"": "aptoslabs/validator:mainnet",
	},
	chainsv1alpha2.ChainArbitrum: {
		"": "offchainlabs/nitro-node:v3.11.4-7d5ac27",
	},
	chainsv1alpha2.ChainAurora: {
		"": "",
	},
	chainsv1alpha2.ChainAvalanche: {
		"": "avaplatform/avalanchego:v1.15.0",
	},
	chainsv1alpha2.ChainAxelar: {
		"": "axelarnet/axelar-core:v1.5.5",
	},
	chainsv1alpha2.ChainBase: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainBerachain: {
		"": "ghcr.io/berachain/beacon-kit:v0.2.0",
	},
	chainsv1alpha2.ChainBitcoin: {
		"": "lncm/bitcoind:v28.0",
	},
	chainsv1alpha2.ChainBitTorrent: {
		"": "",
	},
	chainsv1alpha2.ChainBlast: {
		"": "blastio/blast-geth:mainnet-v1.8.0",
	},
	chainsv1alpha2.ChainBob: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainBobaEth: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainBSC: {
		"": "ghcr.io/bnb-chain/bsc:1.7.8",
	},
	chainsv1alpha2.ChainCardano: {
		"": "ghcr.io/intersectmbo/cardano-node:11.1.3",
	},
	chainsv1alpha2.ChainCelo: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainCore: {
		"": "ghcr.io/coredao-org/core-chain:1.0.26",
	},
	chainsv1alpha2.ChainCosmos: {
		"": "ghcr.io/cosmos/gaia:v28.3.1",
	},
	chainsv1alpha2.ChainCronos: {
		"": "",
	},
	chainsv1alpha2.ChainCronosZkEVM: {
		"": "ghcr.io/cronos-labs/external-node:mainnet-v29.6.0",
	},
	chainsv1alpha2.ChainDash: {
		"": "dashpay/dashd:23.1.8",
	},
	chainsv1alpha2.ChainDogecoin: {
		"": "fiftysix/dogecoin-core:1.14.9",
	},
	chainsv1alpha2.ChainDoma: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainDymension: {
		"": "ghcr.io/dymensionxyz/dymension:4.0.1",
	},
	chainsv1alpha2.ChainEthereum: {
		"":           "nethermind/nethermind:2.0.0",
		"erigon":     "erigontech/erigon:v2.61.3",
		"geth":       "ethereum/client-go:v1.17.7",
		"nethermind": "nethermind/nethermind:2.0.0",
		"reth":       "ghcr.io/paradigmxyz/reth:v1.11.4",
	},
	chainsv1alpha2.ChainEthereumArchive: {
		"":           "nethermind/nethermind:2.0.0",
		"erigon":     "erigontech/erigon:v2.61.3",
		"geth":       "ethereum/client-go:v1.17.7",
		"nethermind": "nethermind/nethermind:2.0.0",
		"reth":       "ghcr.io/paradigmxyz/reth:v1.11.4",
	},
	chainsv1alpha2.ChainEthereumBeacon: {
		"": "sigp/lighthouse:v8.2.3",
	},
	chainsv1alpha2.ChainEthereumClassic: {
		"": "hyperledger/besu:26.9.0",
	},
	chainsv1alpha2.ChainEverclear: {
		"": "offchainlabs/nitro-node:v3.11.4-7d5ac27",
	},
	chainsv1alpha2.ChainEvmos: {
		"": "tharsishq/evmos:v20.0.0",
	},
	chainsv1alpha2.ChainFantom: {
		"": "",
	},
	chainsv1alpha2.ChainFilecoin: {
		"": "filecoin/lotus:v1.36.3",
	},
	chainsv1alpha2.ChainFraxtal: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainFuse: {
		"": "fusenet/node:2.0.2",
	},
	chainsv1alpha2.ChainGnosis: {
		"": "nethermind/nethermind:1.39.3",
	},
	chainsv1alpha2.ChainGnosisBeacon: {
		"": "sigp/lighthouse:v8.2.3",
	},
	chainsv1alpha2.ChainGoat: {
		"": "ghcr.io/goatnetwork/goat-geth:v0.4.2",
	},
	chainsv1alpha2.ChainGravityAlpha: {
		"": "ghcr.io/celestiaorg/nitro:v3.6.8",
	},
	chainsv1alpha2.ChainHaqq: {
		"": "alhaqq/haqq:v1.10.0",
	},
	chainsv1alpha2.ChainHarmony: {
		"": "harmonyone/harmony:v8.5.4",
	},
	chainsv1alpha2.ChainHashKey: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainHemi: {
		"": "hemilabs/op-geth:v1.101408.0",
	},
	chainsv1alpha2.ChainHyperliquid: {
		"": "",
	},
	chainsv1alpha2.ChainImmutableZkEVM: {
		"": "ghcr.io/immutable/immutable-geth/immutable-geth:v1.0.0",
	},
	chainsv1alpha2.ChainInk: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainKatana: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainKava: {
		"": "kava/kava:v0.28.2-goleveldb",
	},
	chainsv1alpha2.ChainKlaytn: {
		"": "klaytn/klaytn:v2.2.0",
	},
	chainsv1alpha2.ChainKroma: {
		"": "kromanetwork/geth:v0.6.3",
	},
	chainsv1alpha2.ChainKusama: {
		"": "parity/polkadot:v1.24.2",
	},
	chainsv1alpha2.ChainLens: {
		"": "matterlabs/external-node:v29.17.0",
	},
	chainsv1alpha2.ChainLinea: {
		"": "",
	},
	chainsv1alpha2.ChainLisk: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainLitecoin: {
		"": "uphold/litecoin-core:0.21",
	},
	chainsv1alpha2.ChainMantaPacific: {
		"": "public.ecr.aws/i6b2w2n6/op-geth:7.1.0",
	},
	chainsv1alpha2.ChainMantle: {
		"": "mantlenetworkio/op-geth:v1.0.3",
	},
	chainsv1alpha2.ChainMegaETH: {
		"": "",
	},
	chainsv1alpha2.ChainMetis: {
		"": "metisdao/l2geth:v0.3.9",
	},
	chainsv1alpha2.ChainMezo: {
		"": "mezo/mezod:v11.0.1",
	},
	chainsv1alpha2.ChainMoca: {
		"": "moca-network/moca:v0.1.0",
	},
	chainsv1alpha2.ChainMode: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainMonad: {
		"": "",
	},
	chainsv1alpha2.ChainMoonbeam: {
		"": "moonbeamfoundation/moonbeam:v0.52.3",
	},
	chainsv1alpha2.ChainMoonriver: {
		"": "moonbeamfoundation/moonbeam:v0.52.3",
	},
	chainsv1alpha2.ChainMorph: {
		"": "ghcr.io/morph-l2/node:0.5.7",
	},
	chainsv1alpha2.ChainNear: {
		"": "nearprotocol/nearcore:2.13.4",
	},
	chainsv1alpha2.ChainOpBNB: {
		"": "ghcr.io/bnb-chain/op-geth:v0.5.11",
	},
	chainsv1alpha2.ChainOptimism: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainOsmosis: {
		"": "osmolabs/osmosis:v31.0.0",
	},
	chainsv1alpha2.ChainPlasma: {
		"": "ghcr.io/plasmalaboratories/plasma-consensus-public:0.15.0",
	},
	chainsv1alpha2.ChainPlaynance: {
		"": "offchainlabs/nitro-node:v3.11.4-7d5ac27",
	},
	chainsv1alpha2.ChainPlume: {
		"": "public.ecr.aws/i6b2w2n6/nitro-node:plume-v2.3.2",
	},
	chainsv1alpha2.ChainPolkadot: {
		"": "parity/polkadot:v1.24.2",
	},
	chainsv1alpha2.ChainPolygon: {
		"": "0xpolygon/bor:2.10.1",
	},
	chainsv1alpha2.ChainPolygonZkEVM: {
		"": "ghcr.io/0xpolygon/cdk-erigon:v2.64.2",
	},
	chainsv1alpha2.ChainRonin: {
		"": "",
	},
	chainsv1alpha2.ChainRootstock: {
		"": "rsksmart/rskj:ARROWHEAD-6.5.1",
	},
	chainsv1alpha2.ChainScroll: {
		"": "scrolltech/l2geth:scroll-v5.10.10",
	},
	chainsv1alpha2.ChainSei: {
		"": "ghcr.io/sei-protocol/sei:v6.6.3",
	},
	chainsv1alpha2.ChainShibarium: {
		"": "",
	},
	chainsv1alpha2.ChainSolana: {
		"": "anzaxyz/agave:v3.1.14",
	},
	chainsv1alpha2.ChainSoneium: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainSonic: {
		"": "",
	},
	chainsv1alpha2.ChainStarknet: {
		"": "nethermindeth/juno:v0.16.7",
	},
	chainsv1alpha2.ChainStellar: {
		"": "stellar/stellar-core:29.0.0-3589.4eb833373.noble",
	},
	chainsv1alpha2.ChainSui: {
		"": "mysten/sui-node:mainnet-v1.80.1",
	},
	chainsv1alpha2.ChainSuperseed: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainSwell: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainTaiko: {
		"": "us-docker.pkg.dev/evmchain/images/taiko-geth:v2.7.0",
	},
	chainsv1alpha2.ChainTelos: {
		"": "",
	},
	chainsv1alpha2.ChainThundercore: {
		"": "thundercore/thunder:r4.3.8",
	},
	chainsv1alpha2.ChainTON: {
		"": "ghcr.io/ton-blockchain/ton:v2026.02-1",
	},
	chainsv1alpha2.ChainTRON: {
		"": "tronprotocol/java-tron:GreatVoyage-v4.8.2",
	},
	chainsv1alpha2.ChainUnichain: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainViction: {
		"": "buildonviction/node:v2.6.1",
	},
	chainsv1alpha2.ChainWemix: {
		"": "",
	},
	chainsv1alpha2.ChainWorldchain: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainXRP: {
		"": "xrpllabsofficial/xrpld:3.3.0",
	},
	chainsv1alpha2.ChainZeroNetwork: {
		"": "matterlabs/external-node:v29.17.0",
	},
	chainsv1alpha2.ChainZircuit: {
		"": "",
	},
	chainsv1alpha2.ChainZkSync: {
		"": "matterlabs/external-node:v29.17.0",
	},
	chainsv1alpha2.ChainZora: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
}

// DefaultImageFor returns the default container image for a chain and client.
// Falls back to the chain default (key "") when the client has no dedicated entry.
func DefaultImageFor(chain chainsv1alpha2.Chain, client string) string {
	clients, ok := chainDefaultImages[chain]
	if !ok {
		return ""
	}
	if img, ok := clients[strings.ToLower(client)]; ok {
		return img
	}
	return clients[""]
}
