// Code generated by cmd/versioncheck on 2026-04-29. DO NOT EDIT.

package adapters

import (
	"strings"

	nodesv1alpha1 "github.com/tazhate/chainplane/api/v1alpha1"
)

//go:generate go run ../../cmd/versioncheck --update

// chainDefaultImages maps each chain and optional client to its default container image.
// Inner key: lowercase client name, or "" for the chain default.
var chainDefaultImages = map[nodesv1alpha1.Chain]map[string]string{
	nodesv1alpha1.ChainAbstract: {
		"": "matterlabs/external-node:v24.5.0",
	},
	nodesv1alpha1.ChainAptos: {
		"": "aptoslabs/validator:mainnet",
	},
	nodesv1alpha1.ChainArbitrum: {
		"": "offchainlabs/nitro-node:v3.9.7",
	},
	nodesv1alpha1.ChainAurora: {
		"": "nearaurora/srpc2-relayer:latest",
	},
	nodesv1alpha1.ChainAvalanche: {
		"": "avaplatform/avalanchego:v1.14.1",
	},
	nodesv1alpha1.ChainAxelar: {
		"": "axelarnet/axelar-core:v1.4.4",
	},
	nodesv1alpha1.ChainBase: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101411.2",
	},
	nodesv1alpha1.ChainBerachain: {
		"": "ghcr.io/berachain/beacon-kit:v0.2.0",
	},
	nodesv1alpha1.ChainBitcoin: {
		"": "lncm/bitcoind:v28.0",
	},
	nodesv1alpha1.ChainBitTorrent: {
		"": "bttcprotocol/bttc:v1.0.3",
	},
	nodesv1alpha1.ChainBlast: {
		"": "blastio/blast-geth:mainnet-v1.8.0",
	},
	nodesv1alpha1.ChainBob: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101408.0",
	},
	nodesv1alpha1.ChainBobaEth: {
		"": "bobanetwork/op-geth:v1.101411.4",
	},
	nodesv1alpha1.ChainBSC: {
		"": "ghcr.io/bnb-chain/bsc:1.6.7",
	},
	nodesv1alpha1.ChainCardano: {
		"": "ghcr.io/intersectmbo/cardano-node:10.6.2",
	},
	nodesv1alpha1.ChainCelo: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101603.5",
	},
	nodesv1alpha1.ChainCore: {
		"": "coredao/core-chain:v1.0.22",
	},
	nodesv1alpha1.ChainCosmos: {
		"": "ghcr.io/cosmos/gaia:v27.0.0",
	},
	nodesv1alpha1.ChainCronos: {
		"": "crypto-org-chain/cronos:v1.4.4",
	},
	nodesv1alpha1.ChainCronosZkEVM: {
		"": "ghcr.io/cronos-labs/external-node:mainnet-v29.6.0",
	},
	nodesv1alpha1.ChainDash: {
		"": "dashpay/dashd:23.1.2",
	},
	nodesv1alpha1.ChainDogecoin: {
		"": "ruimarinho/dogecoin:1-alpine",
	},
	nodesv1alpha1.ChainDoma: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101408.0",
	},
	nodesv1alpha1.ChainDymension: {
		"": "dymensionxyz/dymd:v3.1.0",
	},
	nodesv1alpha1.ChainEthereum: {
		"":           "nethermind/nethermind:1.37.1",
		"erigon":     "erigontech/erigon:v2.61.3",
		"geth":       "ethereum/client-go:v1.17.1",
		"nethermind": "nethermind/nethermind:1.36.1",
		"reth":       "ghcr.io/paradigmxyz/reth:v1.11.3",
	},
	nodesv1alpha1.ChainEthereumArchive: {
		"":           "nethermind/nethermind:1.37.1",
		"erigon":     "erigontech/erigon:v2.61.3",
		"geth":       "ethereum/client-go:v1.17.1",
		"nethermind": "nethermind/nethermind:1.36.1",
		"reth":       "ghcr.io/paradigmxyz/reth:v1.11.3",
	},
	nodesv1alpha1.ChainEthereumBeacon: {
		"": "sigp/lighthouse:v8.1.3",
	},
	nodesv1alpha1.ChainEthereumClassic: {
		"": "hyperledger/besu:26.4.0",
	},
	nodesv1alpha1.ChainEverclear: {
		"": "offchainlabs/nitro-node:v3.6.0",
	},
	nodesv1alpha1.ChainEvmos: {
		"": "tharsishq/evmos:v20.0.0",
	},
	nodesv1alpha1.ChainFantom: {
		"": "fantomfoundation/go-opera:v1.1.3-txtracing",
	},
	nodesv1alpha1.ChainFilecoin: {
		"": "filecoin/lotus:v1.35.1",
	},
	nodesv1alpha1.ChainFraxtal: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101408.0",
	},
	nodesv1alpha1.ChainFuse: {
		"": "fusenet/node:2.0.2",
	},
	nodesv1alpha1.ChainGnosis: {
		"": "nethermind/nethermind:1.37.1",
	},
	nodesv1alpha1.ChainGnosisBeacon: {
		"": "sigp/lighthouse:v8.1.3",
	},
	nodesv1alpha1.ChainGoat: {
		"": "ghcr.io/goatnetwork/goat-geth:v0.4.2",
	},
	nodesv1alpha1.ChainGravityAlpha: {
		"": "ghcr.io/celestiaorg/nitro:v3.6.8",
	},
	nodesv1alpha1.ChainHaqq: {
		"": "alhaqq/haqq:v1.9.3",
	},
	nodesv1alpha1.ChainHarmony: {
		"": "harmonyone/harmony:v8.5.4",
	},
	nodesv1alpha1.ChainHashKey: {
		"": "hashkeychain/hashkey-geth:v1.0.0",
	},
	nodesv1alpha1.ChainHemi: {
		"": "hemilabs/op-geth:v1.101408.0",
	},
	nodesv1alpha1.ChainHyperliquid: {
		"": "hyperliquid/hl-node:latest",
	},
	nodesv1alpha1.ChainImmutableZkEVM: {
		"": "ghcr.io/immutable/immutable-geth/immutable-geth:v1.0.0",
	},
	nodesv1alpha1.ChainInk: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101408.0",
	},
	nodesv1alpha1.ChainKatana: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101408.0",
	},
	nodesv1alpha1.ChainKava: {
		"": "kava-labs/kava:v0.26.2",
	},
	nodesv1alpha1.ChainKlaytn: {
		"": "klaytn/klaytn:v2.2.0",
	},
	nodesv1alpha1.ChainKroma: {
		"": "kromanetwork/geth:v0.6.3",
	},
	nodesv1alpha1.ChainKusama: {
		"": "parity/polkadot:v1.22.0",
	},
	nodesv1alpha1.ChainLens: {
		"": "matterlabs/external-node:v24.5.0",
	},
	nodesv1alpha1.ChainLinea: {
		"": "consensys/linea-besu:24.12.2",
	},
	nodesv1alpha1.ChainLisk: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101603.5",
	},
	nodesv1alpha1.ChainLitecoin: {
		"": "uphold/litecoin-core:0.21",
	},
	nodesv1alpha1.ChainMantaPacific: {
		"": "mantanetwork/op-geth:v1.101304.3",
	},
	nodesv1alpha1.ChainMantle: {
		"": "mantlenetworkio/op-geth:v1.0.3",
	},
	nodesv1alpha1.ChainMegaETH: {
		"": "megaeth-labs/node:latest",
	},
	nodesv1alpha1.ChainMetis: {
		"": "metisprotocol/l2geth:v1.4.2",
	},
	nodesv1alpha1.ChainMezo: {
		"": "mezo/mezod:v9.0.0",
	},
	nodesv1alpha1.ChainMoca: {
		"": "moca-network/moca:v0.1.0",
	},
	nodesv1alpha1.ChainMode: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101411.2",
	},
	nodesv1alpha1.ChainMonad: {
		"": "monadlabs/monad-node:latest",
	},
	nodesv1alpha1.ChainMoonbeam: {
		"": "moonbeamfoundation/moonbeam:v0.51.0",
	},
	nodesv1alpha1.ChainMoonriver: {
		"": "moonbeamfoundation/moonbeam:v0.51.0",
	},
	nodesv1alpha1.ChainMorph: {
		"": "ghcr.io/morphprotocol/node:v0.3.0",
	},
	nodesv1alpha1.ChainNear: {
		"": "nearprotocol/nearcore:2.10.7",
	},
	nodesv1alpha1.ChainOpBNB: {
		"": "ghcr.io/bnb-chain/op-geth:v0.5.2",
	},
	nodesv1alpha1.ChainOptimism: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101411.2",
	},
	nodesv1alpha1.ChainOsmosis: {
		"": "osmolabs/osmosis:v31.0.0",
	},
	nodesv1alpha1.ChainPlasma: {
		"": "plasma-next/node:v0.1.0",
	},
	nodesv1alpha1.ChainPlaynance: {
		"": "offchainlabs/nitro-node:v3.6.0",
	},
	nodesv1alpha1.ChainPlume: {
		"": "public.ecr.aws/i6b2w2n6/nitro-node:plume-v2.3.2",
	},
	nodesv1alpha1.ChainPolkadot: {
		"": "parity/polkadot:v1.22.0",
	},
	nodesv1alpha1.ChainPolygon: {
		"": "0xpolygon/bor:2.7.2",
	},
	nodesv1alpha1.ChainPolygonZkEVM: {
		"": "0xpolygonhermez/zkevm-node:v0.7.0",
	},
	nodesv1alpha1.ChainRonin: {
		"": "ghcr.io/ronin-chain/ronin:v2.8.3",
	},
	nodesv1alpha1.ChainRootstock: {
		"": "rsksmart/rskj:ARROWHEAD-6.5.1",
	},
	nodesv1alpha1.ChainScroll: {
		"": "scrolltech/l2geth:scroll-v5.10.6",
	},
	nodesv1alpha1.ChainSei: {
		"": "seiprotocol/seid:v6.2.0",
	},
	nodesv1alpha1.ChainShibarium: {
		"": "shibaone/bor:v1.3.7-bone",
	},
	nodesv1alpha1.ChainSolana: {
		"": "solanalabs/agave:v2.1.0",
	},
	nodesv1alpha1.ChainSoneium: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101408.0",
	},
	nodesv1alpha1.ChainSonic: {
		"": "ghcr.io/0xsoniclabs/sonic:v2.1.6",
	},
	nodesv1alpha1.ChainStarknet: {
		"": "nethermindeth/juno:v0.16.0",
	},
	nodesv1alpha1.ChainStellar: {
		"": "stellar/stellar-core:v19.12.0",
	},
	nodesv1alpha1.ChainSui: {
		"": "mysten/sui-node:v1.39.2",
	},
	nodesv1alpha1.ChainSuperseed: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101408.0",
	},
	nodesv1alpha1.ChainSwell: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101408.0",
	},
	nodesv1alpha1.ChainTaiko: {
		"": "taikoxyz/taiko-geth:v1.8.0",
	},
	nodesv1alpha1.ChainTelos: {
		"": "telosnetwork/telos-evm-rpc:v2.0.0",
	},
	nodesv1alpha1.ChainThundercore: {
		"": "thundercore/thunder:r4.1.3",
	},
	nodesv1alpha1.ChainTON: {
		"": "ghcr.io/ton-blockchain/ton:v2026.02-1",
	},
	nodesv1alpha1.ChainTRON: {
		"": "tronprotocol/java-tron:GreatVoyage-v4.8.1",
	},
	nodesv1alpha1.ChainUnichain: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101608.0",
	},
	nodesv1alpha1.ChainViction: {
		"": "buildonviction/node:v2.5.1",
	},
	nodesv1alpha1.ChainWemix: {
		"": "wemixnetwork/wemix:v1.2.0",
	},
	nodesv1alpha1.ChainWorldchain: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101603.5",
	},
	nodesv1alpha1.ChainXRP: {
		"": "xrpllabsofficial/xrpld:3.1.2",
	},
	nodesv1alpha1.ChainZeroNetwork: {
		"": "matterlabs/external-node:v24.5.0",
	},
	nodesv1alpha1.ChainZircuit: {
		"": "ghcr.io/zircuit-labs/l2-geth-public:v1.0.0",
	},
	nodesv1alpha1.ChainZkSync: {
		"": "matterlabs/external-node:v2.0.22",
	},
	nodesv1alpha1.ChainZora: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101411.2",
	},
}

// DefaultImageFor returns the default container image for a chain and client.
// Falls back to the chain default (key "") when the client has no dedicated entry.
func DefaultImageFor(chain nodesv1alpha1.Chain, client string) string {
	clients, ok := chainDefaultImages[chain]
	if !ok {
		return ""
	}
	if img, ok := clients[strings.ToLower(client)]; ok {
		return img
	}
	return clients[""]
}
