// Code generated by cmd/versioncheck on 2026-06-14. DO NOT EDIT.

package adapters

import (
	"strings"

	chainsv1alpha2 "github.com/tazhate/chainplane/api/v1alpha2"
)

//go:generate go run ../../cmd/versioncheck --update

// chainDefaultImages maps each chain and optional client to its default container image.
// Inner key: lowercase client name, or "" for the chain default.
var chainDefaultImages = map[chainsv1alpha2.Chain]map[string]string{
	chainsv1alpha2.ChainAbstract: {
		"": "matterlabs/external-node:v24.5.0",
	},
	chainsv1alpha2.ChainAptos: {
		"": "aptoslabs/validator:mainnet",
	},
	chainsv1alpha2.ChainArbitrum: {
		"": "offchainlabs/nitro-node:v3.9.7",
	},
	chainsv1alpha2.ChainAurora: {
		"": "nearaurora/srpc2-relayer:latest",
	},
	chainsv1alpha2.ChainAvalanche: {
		"": "avaplatform/avalanchego:v1.14.2",
	},
	chainsv1alpha2.ChainAxelar: {
		"": "axelarnet/axelar-core:v1.4.7",
	},
	chainsv1alpha2.ChainBase: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101603.5",
	},
	chainsv1alpha2.ChainBerachain: {
		"": "ghcr.io/berachain/beacon-kit:v0.2.0",
	},
	chainsv1alpha2.ChainBitcoin: {
		"": "lncm/bitcoind:v28.0",
	},
	chainsv1alpha2.ChainBitTorrent: {
		"": "bttcprotocol/bttc:v1.0.3",
	},
	chainsv1alpha2.ChainBlast: {
		"": "blastio/blast-geth:mainnet-v1.8.0",
	},
	chainsv1alpha2.ChainBob: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.1",
	},
	chainsv1alpha2.ChainBobaEth: {
		"": "bobanetwork/op-geth:v1.101411.4",
	},
	chainsv1alpha2.ChainBSC: {
		"": "ghcr.io/bnb-chain/bsc:1.6.7",
	},
	chainsv1alpha2.ChainCardano: {
		"": "ghcr.io/intersectmbo/cardano-node:10.6.2",
	},
	chainsv1alpha2.ChainCelo: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainCore: {
		"": "coredao/core-chain:v1.0.22",
	},
	chainsv1alpha2.ChainCosmos: {
		"": "ghcr.io/cosmos/gaia:v27.0.0",
	},
	chainsv1alpha2.ChainCronos: {
		"": "crypto-org-chain/cronos:v1.4.4",
	},
	chainsv1alpha2.ChainCronosZkEVM: {
		"": "ghcr.io/cronos-labs/external-node:mainnet-v29.6.0",
	},
	chainsv1alpha2.ChainDash: {
		"": "dashpay/dashd:23.1.3",
	},
	chainsv1alpha2.ChainDogecoin: {
		"": "fiftysix/dogecoin-core:1.14.9",
	},
	chainsv1alpha2.ChainDoma: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.1",
	},
	chainsv1alpha2.ChainDymension: {
		"": "dymensionxyz/dymd:v3.1.0",
	},
	chainsv1alpha2.ChainEthereum: {
		"":           "nethermind/nethermind:1.38.0",
		"erigon":     "erigontech/erigon:v2.61.3",
		"geth":       "ethereum/client-go:v1.17.1",
		"nethermind": "nethermind/nethermind:1.36.1",
		"reth":       "ghcr.io/paradigmxyz/reth:v1.11.3",
	},
	chainsv1alpha2.ChainEthereumArchive: {
		"":           "nethermind/nethermind:1.38.0",
		"erigon":     "erigontech/erigon:v2.61.3",
		"geth":       "ethereum/client-go:v1.17.1",
		"nethermind": "nethermind/nethermind:1.36.1",
		"reth":       "ghcr.io/paradigmxyz/reth:v1.11.3",
	},
	chainsv1alpha2.ChainEthereumBeacon: {
		"": "sigp/lighthouse:v8.1.3",
	},
	chainsv1alpha2.ChainEthereumClassic: {
		"": "hyperledger/besu:26.6.0",
	},
	chainsv1alpha2.ChainEverclear: {
		"": "offchainlabs/nitro-node:v3.6.0",
	},
	chainsv1alpha2.ChainEvmos: {
		"": "tharsishq/evmos:v20.0.0",
	},
	chainsv1alpha2.ChainFantom: {
		"": "fantomfoundation/go-opera:v1.1.3-txtracing",
	},
	chainsv1alpha2.ChainFilecoin: {
		"": "filecoin/lotus:v1.36.0",
	},
	chainsv1alpha2.ChainFraxtal: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101511.1",
	},
	chainsv1alpha2.ChainFuse: {
		"": "fusenet/node:2.0.2",
	},
	chainsv1alpha2.ChainGnosis: {
		"": "nethermind/nethermind:1.38.0",
	},
	chainsv1alpha2.ChainGnosisBeacon: {
		"": "sigp/lighthouse:v8.1.3",
	},
	chainsv1alpha2.ChainGoat: {
		"": "ghcr.io/goatnetwork/goat-geth:v0.4.2",
	},
	chainsv1alpha2.ChainGravityAlpha: {
		"": "ghcr.io/celestiaorg/nitro:v3.6.8",
	},
	chainsv1alpha2.ChainHaqq: {
		"": "alhaqq/haqq:v1.9.4",
	},
	chainsv1alpha2.ChainHarmony: {
		"": "harmonyone/harmony:v8.5.4",
	},
	chainsv1alpha2.ChainHashKey: {
		"": "hashkeychain/hashkey-geth:v1.0.0",
	},
	chainsv1alpha2.ChainHemi: {
		"": "hemilabs/op-geth:v1.101408.0",
	},
	chainsv1alpha2.ChainHyperliquid: {
		"": "hyperliquid/hl-node:latest",
	},
	chainsv1alpha2.ChainImmutableZkEVM: {
		"": "ghcr.io/immutable/immutable-geth/immutable-geth:v1.0.0",
	},
	chainsv1alpha2.ChainInk: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.1",
	},
	chainsv1alpha2.ChainKatana: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101604.0",
	},
	chainsv1alpha2.ChainKava: {
		"": "kava-labs/kava:v0.26.2",
	},
	chainsv1alpha2.ChainKlaytn: {
		"": "klaytn/klaytn:v2.2.0",
	},
	chainsv1alpha2.ChainKroma: {
		"": "kromanetwork/geth:v0.6.3",
	},
	chainsv1alpha2.ChainKusama: {
		"": "parity/polkadot:v1.22.3",
	},
	chainsv1alpha2.ChainLens: {
		"": "matterlabs/external-node:v24.5.0",
	},
	chainsv1alpha2.ChainLinea: {
		"": "consensys/linea-besu:24.12.2",
	},
	chainsv1alpha2.ChainLisk: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainLitecoin: {
		"": "uphold/litecoin-core:0.21",
	},
	chainsv1alpha2.ChainMantaPacific: {
		"": "mantanetwork/op-geth:v1.101304.3",
	},
	chainsv1alpha2.ChainMantle: {
		"": "mantlenetworkio/op-geth:v1.0.3",
	},
	chainsv1alpha2.ChainMegaETH: {
		"": "megaeth-labs/node:latest",
	},
	chainsv1alpha2.ChainMetis: {
		"": "metisprotocol/l2geth:v1.4.2",
	},
	chainsv1alpha2.ChainMezo: {
		"": "mezo/mezod:v9.1.0",
	},
	chainsv1alpha2.ChainMoca: {
		"": "moca-network/moca:v0.1.0",
	},
	chainsv1alpha2.ChainMode: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.1",
	},
	chainsv1alpha2.ChainMonad: {
		"": "monadlabs/monad-node:latest",
	},
	chainsv1alpha2.ChainMoonbeam: {
		"": "moonbeamfoundation/moonbeam:v0.52.0",
	},
	chainsv1alpha2.ChainMoonriver: {
		"": "moonbeamfoundation/moonbeam:v0.52.0",
	},
	chainsv1alpha2.ChainMorph: {
		"": "ghcr.io/morph-l2/node:0.5.7",
	},
	chainsv1alpha2.ChainNear: {
		"": "nearprotocol/nearcore:2.10.7",
	},
	chainsv1alpha2.ChainOpBNB: {
		"": "ghcr.io/bnb-chain/op-geth:v0.5.2",
	},
	chainsv1alpha2.ChainOptimism: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.1",
	},
	chainsv1alpha2.ChainOsmosis: {
		"": "osmolabs/osmosis:v31.0.0",
	},
	chainsv1alpha2.ChainPlasma: {
		"": "plasma-next/node:v0.1.0",
	},
	chainsv1alpha2.ChainPlaynance: {
		"": "offchainlabs/nitro-node:v3.6.0",
	},
	chainsv1alpha2.ChainPlume: {
		"": "public.ecr.aws/i6b2w2n6/nitro-node:plume-v2.3.2",
	},
	chainsv1alpha2.ChainPolkadot: {
		"": "parity/polkadot:v1.22.3",
	},
	chainsv1alpha2.ChainPolygon: {
		"": "0xpolygon/bor:2.8.3",
	},
	chainsv1alpha2.ChainPolygonZkEVM: {
		"": "0xpolygonhermez/zkevm-node:v0.7.0",
	},
	chainsv1alpha2.ChainRonin: {
		"": "ghcr.io/ronin-chain/ronin:v2.8.3",
	},
	chainsv1alpha2.ChainRootstock: {
		"": "rsksmart/rskj:ARROWHEAD-6.5.1",
	},
	chainsv1alpha2.ChainScroll: {
		"": "scrolltech/l2geth:scroll-v5.10.6",
	},
	chainsv1alpha2.ChainSei: {
		"": "seiprotocol/seid:v6.2.0",
	},
	chainsv1alpha2.ChainShibarium: {
		"": "shibaone/bor:v1.3.7-bone",
	},
	chainsv1alpha2.ChainSolana: {
		"": "solanalabs/agave:v2.1.0",
	},
	chainsv1alpha2.ChainSoneium: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101701.0",
	},
	chainsv1alpha2.ChainSonic: {
		"": "ghcr.io/0xsoniclabs/sonic:v2.1.6",
	},
	chainsv1alpha2.ChainStarknet: {
		"": "nethermindeth/juno:v0.16.2",
	},
	chainsv1alpha2.ChainStellar: {
		"": "stellar/stellar-core:v19.12.0",
	},
	chainsv1alpha2.ChainSui: {
		"": "mysten/sui-node:mainnet-v1.72.5",
	},
	chainsv1alpha2.ChainSuperseed: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.2",
	},
	chainsv1alpha2.ChainSwell: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101701.0",
	},
	chainsv1alpha2.ChainTaiko: {
		"": "taikoxyz/taiko-geth:v1.8.0",
	},
	chainsv1alpha2.ChainTelos: {
		"": "telosnetwork/telos-evm-rpc:v2.0.0",
	},
	chainsv1alpha2.ChainThundercore: {
		"": "thundercore/thunder:r4.1.3",
	},
	chainsv1alpha2.ChainTON: {
		"": "ghcr.io/ton-blockchain/ton:v2026.02-1",
	},
	chainsv1alpha2.ChainTRON: {
		"": "tronprotocol/java-tron:GreatVoyage-v4.8.1",
	},
	chainsv1alpha2.ChainUnichain: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101609.0",
	},
	chainsv1alpha2.ChainViction: {
		"": "buildonviction/node:v2.6.0",
	},
	chainsv1alpha2.ChainWemix: {
		"": "wemixnetwork/wemix:v1.2.0",
	},
	chainsv1alpha2.ChainWorldchain: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101702.0",
	},
	chainsv1alpha2.ChainXRP: {
		"": "xrpllabsofficial/xrpld:3.1.3",
	},
	chainsv1alpha2.ChainZeroNetwork: {
		"": "matterlabs/external-node:v24.5.0",
	},
	chainsv1alpha2.ChainZircuit: {
		"": "ghcr.io/zircuit-labs/l2-geth-public:v1.0.0",
	},
	chainsv1alpha2.ChainZkSync: {
		"": "matterlabs/external-node:v2.0.22",
	},
	chainsv1alpha2.ChainZora: {
		"": "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101609.1",
	},
}

// DefaultImageFor returns the default container image for a chain and client.
// Falls back to the chain default (key "") when the client has no dedicated entry.
func DefaultImageFor(chain chainsv1alpha2.Chain, client string) string {
	clients, ok := chainDefaultImages[chain]
	if !ok {
		return ""
	}
	if img, ok := clients[strings.ToLower(client)]; ok {
		return img
	}
	return clients[""]
}
