## Append samples of your project ##
resources:
- nodes_v1alpha1_blockchainnode.yaml
- nodes_v1alpha1_blockchainnode_bitcoin.yaml
- nodes_v1alpha1_blockchainnode_ethereum.yaml
- nodes_v1alpha1_blockchainnode_ethereum_archive.yaml
- nodes_v1alpha1_blockchainnode_solana.yaml
- nodes_v1alpha1_blockchainnode_bsc.yaml
- nodes_v1alpha1_blockchainnode_tron.yaml
- nodes_v1alpha1_blockchainnode_polygon.yaml
- nodes_v1alpha1_blockchainnode_avalanche.yaml
- nodes_v1alpha1_blockchainnode_litecoin.yaml
- nodes_v1alpha1_blockchainnode_xrp.yaml
- nodes_v1alpha1_blockchainnode_stellar.yaml
- nodes_v1alpha1_blockchainnode_dash.yaml
- nodes_v1alpha1_blockchainnode_ton.yaml
- nodes_v1alpha1_blockchainnode_cosmos.yaml
- nodes_v1alpha1_blockchainnode_near.yaml
- nodes_v1alpha1_blockchainnode_sui.yaml
- nodes_v1alpha1_blockchainnode_aptos.yaml
- nodes_v1alpha1_blockchainnode_cardano.yaml
- nodes_v1alpha1_blockchainnode_arbitrum.yaml
- nodes_v1alpha1_blockchainnode_optimism.yaml
- nodes_v1alpha1_blockchainnode_base.yaml
- nodes_v1alpha1_blockchainnode_fantom.yaml
- nodes_v1alpha1_blockchainnode_gnosis.yaml
- nodes_v1alpha1_blockchainnode_mantle.yaml
- nodes_v1alpha1_blockchainnode_berachain.yaml
- nodes_v1alpha1_blockchainnode_cronos.yaml
- nodes_v1alpha1_blockchainnode_ronin.yaml
- nodes_v1alpha1_blockchainnode_celo.yaml
- nodes_v1alpha1_blockchainnode_blast.yaml
- nodes_v1alpha1_blockchainnode_mode.yaml
- nodes_v1alpha1_blockchainnode_zora.yaml
- nodes_v1alpha1_blockchainnode_taiko.yaml
- nodes_v1alpha1_blockchainnode_zksync.yaml
- nodes_v1alpha1_blockchainnode_linea.yaml
- nodes_v1alpha1_blockchainnode_scroll.yaml
- nodes_v1alpha1_blockchainnode_dogecoin.yaml
- nodes_v1alpha1_blockchainnode_osmosis.yaml
- nodes_v1alpha1_blockchainnode_sei.yaml
- nodes_v1alpha1_blockchainnode_evmos.yaml
- nodes_v1alpha1_blockchainnode_kava.yaml
- nodes_v1alpha1_blockchainnode_polkadot.yaml
- nodes_v1alpha1_blockchainnode_starknet.yaml
- nodes_v1alpha1_blockchainnode_filecoin.yaml
- nodes_v1alpha1_blockchainnode_moonbeam.yaml
- nodes_v1alpha1_blockchainnode_moonriver.yaml
- nodes_v1alpha1_blockchainnode_polygon_zkevm.yaml
- nodes_v1alpha1_blockchainnode_manta_pacific.yaml
- nodes_v1alpha1_blockchainnode_metis.yaml
- nodes_v1alpha1_blockchainnode_fraxtal.yaml
- nodes_v1alpha1_blockchainnode_lisk.yaml
- nodes_v1alpha1_blockchainnode_kroma.yaml
- nodes_v1alpha1_blockchainnode_bob.yaml
- nodes_v1alpha1_blockchainnode_boba_eth.yaml
- nodes_v1alpha1_blockchainnode_worldchain.yaml
- nodes_v1alpha1_blockchainnode_unichain.yaml
- nodes_v1alpha1_blockchainnode_lens.yaml
- nodes_v1alpha1_blockchainnode_plume.yaml
- nodes_v1alpha1_blockchainnode_hemi.yaml
- nodes_v1alpha1_blockchainnode_soneium.yaml
- nodes_v1alpha1_blockchainnode_swell.yaml
- nodes_v1alpha1_blockchainnode_superseed.yaml
- nodes_v1alpha1_blockchainnode_ink.yaml
- nodes_v1alpha1_blockchainnode_morph.yaml
- nodes_v1alpha1_blockchainnode_abstract.yaml
- nodes_v1alpha1_blockchainnode_megaeth.yaml
- nodes_v1alpha1_blockchainnode_zero_network.yaml
- nodes_v1alpha1_blockchainnode_zircuit.yaml
- nodes_v1alpha1_blockchainnode_immutable_zkevm.yaml
- nodes_v1alpha1_blockchainnode_axelar.yaml
- nodes_v1alpha1_blockchainnode_dymension.yaml
- nodes_v1alpha1_blockchainnode_bittorrent.yaml
- nodes_v1alpha1_blockchainnode_gravity_alpha.yaml
- nodes_v1alpha1_blockchainnode_moca.yaml
- nodes_v1alpha1_blockchainnode_everclear.yaml
- nodes_v1alpha1_blockchainnode_doma.yaml
- nodes_v1alpha1_blockchainnode_aurora.yaml
- nodes_v1alpha1_blockchainnode_harmony.yaml
- nodes_v1alpha1_blockchainnode_rootstock.yaml
- nodes_v1alpha1_blockchainnode_telos.yaml
- nodes_v1alpha1_blockchainnode_klaytn.yaml
- nodes_v1alpha1_blockchainnode_shibarium.yaml
- nodes_v1alpha1_blockchainnode_core.yaml
- nodes_v1alpha1_blockchainnode_haqq.yaml
- nodes_v1alpha1_blockchainnode_hashkey.yaml
- nodes_v1alpha1_blockchainnode_ethereum-classic.yaml
- nodes_v1alpha1_blockchainnode_opbnb.yaml
- nodes_v1alpha1_blockchainnode_fuse.yaml
- nodes_v1alpha1_blockchainnode_thundercore.yaml
- nodes_v1alpha1_blockchainnode_wemix.yaml
- nodes_v1alpha1_blockchainnode_viction.yaml
- nodes_v1alpha1_blockchainnode_ethereum-beacon.yaml
- nodes_v1alpha1_blockchainnode_gnosis-beacon.yaml
- nodes_v1alpha1_blockchainnode_kusama.yaml
- nodes_v1alpha1_blockchainnode_hyperliquid.yaml
- nodes_v1alpha1_blockchainnode_monad.yaml
- nodes_v1alpha1_blockchainnode_cronos_zkevm.yaml
- nodes_v1alpha1_blockchainnode_sonic.yaml
- nodes_v1alpha1_blockchainnode_goat.yaml
- nodes_v1alpha1_blockchainnode_katana.yaml
- nodes_v1alpha1_blockchainnode_mezo.yaml
- nodes_v1alpha1_blockchainnode_plasma.yaml
- nodes_v1alpha1_blockchainnode_playnance.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
