## Append samples of your project ##
resources:
- nodes_v1alpha1_chaininstance.yaml
- nodes_v1alpha1_chaininstance_bitcoin.yaml
- nodes_v1alpha1_chaininstance_ethereum.yaml
- nodes_v1alpha1_chaininstance_ethereum_archive.yaml
- nodes_v1alpha1_chaininstance_solana.yaml
- nodes_v1alpha1_chaininstance_bsc.yaml
- nodes_v1alpha1_chaininstance_tron.yaml
- nodes_v1alpha1_chaininstance_polygon.yaml
- nodes_v1alpha1_chaininstance_avalanche.yaml
- nodes_v1alpha1_chaininstance_litecoin.yaml
- nodes_v1alpha1_chaininstance_xrp.yaml
- nodes_v1alpha1_chaininstance_stellar.yaml
- nodes_v1alpha1_chaininstance_dash.yaml
- nodes_v1alpha1_chaininstance_ton.yaml
- nodes_v1alpha1_chaininstance_cosmos.yaml
- nodes_v1alpha1_chaininstance_near.yaml
- nodes_v1alpha1_chaininstance_sui.yaml
- nodes_v1alpha1_chaininstance_aptos.yaml
- nodes_v1alpha1_chaininstance_cardano.yaml
- nodes_v1alpha1_chaininstance_arbitrum.yaml
- nodes_v1alpha1_chaininstance_optimism.yaml
- nodes_v1alpha1_chaininstance_base.yaml
- nodes_v1alpha1_chaininstance_fantom.yaml
- nodes_v1alpha1_chaininstance_gnosis.yaml
- nodes_v1alpha1_chaininstance_mantle.yaml
- nodes_v1alpha1_chaininstance_berachain.yaml
- nodes_v1alpha1_chaininstance_cronos.yaml
- nodes_v1alpha1_chaininstance_ronin.yaml
- nodes_v1alpha1_chaininstance_celo.yaml
- nodes_v1alpha1_chaininstance_blast.yaml
- nodes_v1alpha1_chaininstance_mode.yaml
- nodes_v1alpha1_chaininstance_zora.yaml
- nodes_v1alpha1_chaininstance_taiko.yaml
- nodes_v1alpha1_chaininstance_zksync.yaml
- nodes_v1alpha1_chaininstance_linea.yaml
- nodes_v1alpha1_chaininstance_scroll.yaml
- nodes_v1alpha1_chaininstance_dogecoin.yaml
- nodes_v1alpha1_chaininstance_osmosis.yaml
- nodes_v1alpha1_chaininstance_sei.yaml
- nodes_v1alpha1_chaininstance_evmos.yaml
- nodes_v1alpha1_chaininstance_kava.yaml
- nodes_v1alpha1_chaininstance_polkadot.yaml
- nodes_v1alpha1_chaininstance_starknet.yaml
- nodes_v1alpha1_chaininstance_filecoin.yaml
- nodes_v1alpha1_chaininstance_moonbeam.yaml
- nodes_v1alpha1_chaininstance_moonriver.yaml
- nodes_v1alpha1_chaininstance_polygon_zkevm.yaml
- nodes_v1alpha1_chaininstance_manta_pacific.yaml
- nodes_v1alpha1_chaininstance_metis.yaml
- nodes_v1alpha1_chaininstance_fraxtal.yaml
- nodes_v1alpha1_chaininstance_lisk.yaml
- nodes_v1alpha1_chaininstance_kroma.yaml
- nodes_v1alpha1_chaininstance_bob.yaml
- nodes_v1alpha1_chaininstance_boba_eth.yaml
- nodes_v1alpha1_chaininstance_worldchain.yaml
- nodes_v1alpha1_chaininstance_unichain.yaml
- nodes_v1alpha1_chaininstance_lens.yaml
- nodes_v1alpha1_chaininstance_plume.yaml
- nodes_v1alpha1_chaininstance_hemi.yaml
- nodes_v1alpha1_chaininstance_soneium.yaml
- nodes_v1alpha1_chaininstance_swell.yaml
- nodes_v1alpha1_chaininstance_superseed.yaml
- nodes_v1alpha1_chaininstance_ink.yaml
- nodes_v1alpha1_chaininstance_morph.yaml
- nodes_v1alpha1_chaininstance_abstract.yaml
- nodes_v1alpha1_chaininstance_megaeth.yaml
- nodes_v1alpha1_chaininstance_zero_network.yaml
- nodes_v1alpha1_chaininstance_zircuit.yaml
- nodes_v1alpha1_chaininstance_immutable_zkevm.yaml
- nodes_v1alpha1_chaininstance_axelar.yaml
- nodes_v1alpha1_chaininstance_dymension.yaml
- nodes_v1alpha1_chaininstance_bittorrent.yaml
- nodes_v1alpha1_chaininstance_gravity_alpha.yaml
- nodes_v1alpha1_chaininstance_moca.yaml
- nodes_v1alpha1_chaininstance_everclear.yaml
- nodes_v1alpha1_chaininstance_doma.yaml
- nodes_v1alpha1_chaininstance_aurora.yaml
- nodes_v1alpha1_chaininstance_harmony.yaml
- nodes_v1alpha1_chaininstance_rootstock.yaml
- nodes_v1alpha1_chaininstance_telos.yaml
- nodes_v1alpha1_chaininstance_klaytn.yaml
- nodes_v1alpha1_chaininstance_shibarium.yaml
- nodes_v1alpha1_chaininstance_core.yaml
- nodes_v1alpha1_chaininstance_haqq.yaml
- nodes_v1alpha1_chaininstance_hashkey.yaml
- nodes_v1alpha1_chaininstance_ethereum-classic.yaml
- nodes_v1alpha1_chaininstance_opbnb.yaml
- nodes_v1alpha1_chaininstance_fuse.yaml
- nodes_v1alpha1_chaininstance_thundercore.yaml
- nodes_v1alpha1_chaininstance_wemix.yaml
- nodes_v1alpha1_chaininstance_viction.yaml
- nodes_v1alpha1_chaininstance_ethereum-beacon.yaml
- nodes_v1alpha1_chaininstance_gnosis-beacon.yaml
- nodes_v1alpha1_chaininstance_kusama.yaml
- nodes_v1alpha1_chaininstance_hyperliquid.yaml
- nodes_v1alpha1_chaininstance_monad.yaml
- nodes_v1alpha1_chaininstance_cronos_zkevm.yaml
- nodes_v1alpha1_chaininstance_sonic.yaml
- nodes_v1alpha1_chaininstance_goat.yaml
- nodes_v1alpha1_chaininstance_katana.yaml
- nodes_v1alpha1_chaininstance_mezo.yaml
- nodes_v1alpha1_chaininstance_plasma.yaml
- nodes_v1alpha1_chaininstance_playnance.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
