{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "blockchain-node-operator.fullname" . }}-validating
  labels:
    {{- include "blockchain-node-operator.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "blockchain-node-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-nodes-k8s-bch-io-v1alpha1-blockchainnode
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    name: vblockchainnode.kb.io
    rules:
      - apiGroups:
          - nodes.k8s-bch.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - blockchainnodes
    sideEffects: None
{{- end }}
