{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockchain-node-operator.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blockchain-node-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      protocol: TCP
      targetPort: {{ .Values.webhook.service.targetPort }}
  selector:
    {{- include "blockchain-node-operator.selectorLabels" . | nindent 4 }}
{{- end }}
